[package]
name = "rss-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.1.1"
tokio = { version = "1.29", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "tls-native-tls", "sqlite"] }
rss = "2.0.5"
reqwest = "0.11.18"
