name: Build binaries

on:
  push:
    branches:
      - main

jobs:
  windows-msvc-release:
    name: release windows msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-msvc.rss-reader.archive.tar.gz
          path: ./target/release/rss-reader.exe
